# OpportunityPulse developer commands.
# On Windows, run these targets via `make` (Git Bash / WSL) or copy the command.

.DEFAULT_GOAL := help
.PHONY: help install infra up down config migrate revision api worker web lint fmt test eval clean

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

install: ## Install Python deps (editable + dev extras)
	pip install -e ".[dev]"

infra: ## Start Postgres+pgvector and Redis only
	docker compose up -d db redis

up: ## Build and start the full stack
	docker compose up --build

down: ## Stop the stack
	docker compose down

config: ## Validate the compose file
	docker compose config

migrate: ## Apply DB migrations
	cd backend && alembic upgrade head

revision: ## Create a new autogenerated migration (msg="...")
	cd backend && alembic revision --autogenerate -m "$(msg)"

api: ## Run the backend dev server
	cd backend && uvicorn app.main:app --reload

worker: ## Run the Arq worker
	arq worker.arq_app.WorkerSettings

web: ## Run the Next.js dev server
	cd web && npm run dev

lint: ## Lint Python
	ruff check .

fmt: ## Format Python
	ruff format .

test: ## Run tests
	pytest

eval: ## Run the evaluation harness
	python -m evaluation.harness --all

clean: ## Remove caches
	rm -rf .ruff_cache .pytest_cache .mypy_cache **/__pycache__
