"""Initial schema: pgvector extension, all tables, HNSW index.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-11

This first migration enables the ``vector`` extension, then creates the full
schema from the SQLAlchemy model metadata (kept in sync with
``backend/app/models/``), and finally adds the HNSW cosine index used for
embedding retrieval. Later migrations should be hand-authored or autogenerated
diffs against this baseline.
"""

from __future__ import annotations

from alembic import op
from app.db.base import Base
from app.models import *  # noqa: F401,F403  (register all tables on metadata)

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    Base.metadata.create_all(bind=bind)
    # Approximate-nearest-neighbour index for cosine similarity retrieval.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_embeddings_vector_hnsw "
        "ON embeddings USING hnsw (vector vector_cosine_ops)"
    )


def downgrade() -> None:
    bind = op.get_bind()
    op.execute("DROP INDEX IF EXISTS ix_embeddings_vector_hnsw")
    Base.metadata.drop_all(bind=bind)
